run:
  timeout: 5m
  tests: true

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - typecheck
    - misspell
    - gocritic
    - gocyclo

linters-settings:
  gofmt:
    simplify: true
  govet:
    check-shadowing: true
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
  gocyclo:
    min-complexity: 15

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - gocritic
    
    # Exclude mock files
    - path: mock\.go
      linters:
        - gocritic

  max-issues-per-linter: 0
  max-same-issues: 0