package render

import (
	"fmt"
	"sort"
	"strings"
	"time"

	"github.com/yourorg/prtool/internal/model"
)

// Metadata contains information about the render context
type Metadata struct {
	GeneratedAt   time.Time
	TimeRange     string
	TotalPRs      int
	Repositories  []string
	LLMProvider   string
	LLMModel      string
}

// Render generates a Markdown report from PRs and metadata
func Render(meta Metadata, prs []model.PR) string {
	var sb strings.Builder

	// Header
	sb.WriteString("# Pull Request Summary Report\n\n")

	// Metadata section
	sb.WriteString("## Metadata\n\n")
	sb.WriteString(fmt.Sprintf("- **Generated at**: %s\n", meta.GeneratedAt.Format("2006-01-02 15:04:05 MST")))
	sb.WriteString(fmt.Sprintf("- **Time range**: %s\n", meta.TimeRange))
	sb.WriteString(fmt.Sprintf("- **Total PRs**: %d\n", meta.TotalPRs))
	sb.WriteString(fmt.Sprintf("- **Repositories**: %d\n", len(meta.Repositories)))
	
	if meta.LLMProvider != "" && meta.LLMModel != "" {
		sb.WriteString(fmt.Sprintf("- **LLM**: %s (%s)\n", meta.LLMProvider, meta.LLMModel))
	}
	sb.WriteString("\n")

	// Repository list
	if len(meta.Repositories) > 0 && len(meta.Repositories) <= 10 {
		sb.WriteString("### Repositories\n\n")
		for _, repo := range meta.Repositories {
			sb.WriteString(fmt.Sprintf("- %s\n", repo))
		}
		sb.WriteString("\n")
	}

	// PRs by repository
	sb.WriteString("## Pull Requests\n\n")

	if len(prs) == 0 {
		sb.WriteString("*No pull requests found in the specified time range.*")
		return sb.String()
	}

	// Group PRs by repository
	prsByRepo := groupPRsByRepository(prs)

	// Sort repositories for consistent output
	var repos []string
	for repo := range prsByRepo {
		repos = append(repos, repo)
	}
	sort.Strings(repos)

	// Render PRs for each repository
	for _, repo := range repos {
		repoPRs := prsByRepo[repo]
		sb.WriteString(fmt.Sprintf("### %s\n\n", repo))

		for _, pr := range repoPRs {
			// PR header
			sb.WriteString(fmt.Sprintf("#### [#%d](%s) %s\n\n", pr.Number, pr.URL, pr.Title))

			// PR metadata
			sb.WriteString(fmt.Sprintf("- **Author**: @%s\n", pr.Author))
			sb.WriteString(fmt.Sprintf("- **Merged**: %s\n", pr.MergedAt.Format("2006-01-02 15:04 MST")))
			
			if len(pr.Labels) > 0 {
				sb.WriteString(fmt.Sprintf("- **Labels**: %s\n", strings.Join(pr.Labels, ", ")))
			}
			
			sb.WriteString("\n")

			// PR description or summary
			if pr.Summary != "" {
				sb.WriteString("**Summary**:\n")
				sb.WriteString(pr.Summary)
				sb.WriteString("\n\n")
			} else {
				sb.WriteString("**Description**:\n")
				sb.WriteString(formatDescription(pr.Description))
				sb.WriteString("\n\n")
			}
		}
	}

	// Footer
	sb.WriteString("---\n\n")
	sb.WriteString("*Generated by [prtool](https://github.com/yourorg/prtool)*")

	return sb.String()
}

// RenderDryRun generates a simple table format for dry-run mode
func RenderDryRun(prs []model.PR) string {
	if len(prs) == 0 {
		return "No pull requests found.\n"
	}

	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("Found %d pull requests:\n\n", len(prs)))

	// Table header
	sb.WriteString("Repository                    | PR # | Title                                           | Author      | Merged\n")
	sb.WriteString("------------------------------|------|-------------------------------------------------|-------------|------------\n")

	// Table rows
	for _, pr := range prs {
		repo := truncate(pr.Repository, 28)
		title := truncate(pr.Title, 47)
		author := truncate(pr.Author, 11)
		merged := pr.MergedAt.Format("2006-01-02")

		sb.WriteString(fmt.Sprintf("%-29s | %-4d | %-47s | %-11s | %s\n",
			repo, pr.Number, title, author, merged))
	}

	return sb.String()
}

// groupPRsByRepository organizes PRs by their repository
func groupPRsByRepository(prs []model.PR) map[string][]model.PR {
	groups := make(map[string][]model.PR)
	for _, pr := range prs {
		groups[pr.Repository] = append(groups[pr.Repository], pr)
	}
	return groups
}

// formatDescription formats PR description for better readability
func formatDescription(desc string) string {
	if desc == "" {
		return "*No description provided.*"
	}

	// Limit description length
	const maxLength = 500
	if len(desc) > maxLength {
		desc = desc[:maxLength] + "..."
	}

	// Indent each line
	lines := strings.Split(desc, "\n")
	for i, line := range lines {
		if line != "" {
			lines[i] = "> " + line
		}
	}

	return strings.Join(lines, "\n")
}

// truncate shortens a string to the specified length
func truncate(s string, maxLen int) string {
	if len(s) <= maxLen {
		return s
	}
	if maxLen <= 3 {
		return s[:maxLen]
	}
	return s[:maxLen-3] + "..."
}